# Generated by Django 4.2 on 2023-04-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_share', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProtectMusicFile',
            new_name='ProtectedMusicFile',
        ),
    ]
