# Generated by Django 4.2 on 2023-04-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_share', '0004_musicfile_album_musicfile_artist_musicfile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfile',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
