# Generated by Django 4.2 on 2023-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_share', '0005_musicfile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicfile',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='album_art'),
        ),
    ]
